server:
  port: 10010
spring:
  application:
    name: gateway-service # 微服务名称
  cloud:
    nacos:
      discovery:
        # nacos注册中心地址，因为需要拉取服务列表，进行路由转发
        server-addr: 192.168.12.128:8848
    gateway:
      routes:
        - id: sys-service # 微服务名称
          uri: lb://sys-service # 即sys-service服务的负载均衡地址
          predicates: # predicates用于匹配HTTP请求的不同属性
            - Path=/sys/** # 匹配到的URL地址
          filters:
            - StripPrefix=1 # 在转发之前将/sys 去掉