server:
  port: 8081
spring:
  application:
    name: sys-service  #微服务名称
  datasource:
    #数据库连接信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.12.128:3306/nineclock_sys?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 192.168.12.128:8848
  servlet:
    multipart:
      # 文件上传，最大限制，1024 * 1024 = 1M
      max-file-size: 10485760

mybatis-plus:
  # 返回值别名包路径
  type-aliases-package: com.nineclock.system.pojo
  configuration:
    # 返回值字段下划线转驼峰
    map-underscore-to-camel-case: true
    # 输出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    # 设置日志级别
    com.nineclock: debug